server:
  error:
    include-stacktrace: on_param
##?trace=true habilita o stacktrace
  ##port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coffeBreak?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true

    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true